feature/db-challenge2
poissons-d-or/quelcode-db pull request #2
Opened 2021-01-15 16:32 UTC by poissons-d-or

データベース定義書、DDL文の作成

2021-01-15 17:13 UTC, piasoratech requested changes
コメントしたので確認をお願いします

2021-01-15 17:13 UTC, piasoratech commented on db/db-challenge2/db-challenge2.sql
> +  file_name VARCHAR(100),
これ項目として必要ないです

2021-01-15 17:13 UTC, piasoratech commented on db/db-challenge2/db-challenge2.sql
> +CREATE TABLE user_in_chatroom (
テーブル名は複数形にしましょう

2021-01-15 17:13 UTC, piasoratech commented on db/db-challenge2/db-challenge2.sql
> +  completed TINYINT(1) DEFAULT 0 NOT NULL,
フラグメント系のカラムは`is_xxxx`の形にしましょう

2021-01-15 17:13 UTC, piasoratech commented on db/db-challenge2/db-challenge2.sql
> +  file_enabled TINYINT(1) DEFAULT 1 NOT NULL,
これもフラグメント系なので`is_xxxx`の形にしましょう

2021-01-16 14:57 UTC, poissons-d-or commented on db/db-challenge2/db-challenge2.sql
> +  completed TINYINT(1) DEFAULT 0 NOT NULL,
修正しました

2021-01-16 14:58 UTC, poissons-d-or commented on db/db-challenge2/db-challenge2.sql
> +  file_name VARCHAR(100),
ポカミスです。削除しました。

2021-01-16 14:58 UTC, poissons-d-or commented on db/db-challenge2/db-challenge2.sql
> +CREATE TABLE user_in_chatroom (
修正しました。

2021-01-16 14:59 UTC, poissons-d-or commented on db/db-challenge2/db-challenge2.sql
> +  file_enabled TINYINT(1) DEFAULT 1 NOT NULL,
修正しました。

2021-01-17 14:49 UTC, gacha1987 reviewed
コメントしました。
必要であれば定義所の方も修正してください。

2021-01-17 14:49 UTC, gacha1987 commented on db/db-challenge2/db-challenge2.sql
> +  assigned_user_id INT(11) NOT NULL,
usersのIDなので作成者や更新者と同じく外部キー制約の指定が必要です。

2021-01-18 13:55 UTC, poissons-d-or commented on db/db-challenge2/db-challenge2.sql
> +  assigned_user_id INT(11) NOT NULL,
見落としていました。
外部キー制約を指定しました。

2021-01-18 14:24 UTC, piasoratech requested changes
データベース定義書の作成・更新日時系のデフォルト値の記載が無いので、確認して修正しましょう

2021-01-20 16:09 UTC, gacha1987 commented
LGTMです。

2021-01-21 02:35 UTC, merged